name: Build Release Candidate

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      use-rc-index: true
      create-release: true
      release-is-prerelease: true
      release-name-prefix: 'Release Candidate'
      deploy: true
      deploy-destination-dir: 'release-candidate'
      deploy-keep-files: true
    secrets: inherit
