name: Build Main

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      create-release: true
      release-is-prerelease: false
      release-name-prefix: 'Release'
      deploy: true
    secrets: inherit
